// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         prompt_id: "prompt_id"
 *     }
 */
export interface CtaClickRequest {
    /** The ID of the CTA */
    id: string;
    prompt_id: string;
}
