// This file was auto-generated by Fern from our API Definition.

import type * as ApologistAgent from "../../../index.js";

export interface ResumeAgentResponse {
    data?: ApologistAgent.AgentPauseState | undefined;
}
