// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as ApologistAgent from "../index.js";

export class UnprocessableEntityError extends errors.ApologistAgentError {
    public declare readonly body: ApologistAgent.Error_;

    constructor(body: ApologistAgent.Error_, rawResponse?: core.RawResponse) {
        super({
            message: "UnprocessableEntityError",
            statusCode: 422,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "UnprocessableEntityError";
    }
}
