// This file was auto-generated by Fern from our API Definition.

import type * as ApologistAgent from "../../../index.js";

export interface PauseConversationResponse {
    data?: ApologistAgent.Conversation | undefined;
}
