// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         feedback: "feedback"
 *     }
 */
export interface FeedbackRequest {
    /** The ID of the chat completion */
    id: string;
    feedback: string;
}
