// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         flagged: true
 *     }
 */
export interface FlagRequest {
    /** The ID of the chat completion */
    id: string;
    flagged: boolean;
}
