// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetChatCompletionRequest {
    /** The numeric id or UUID of the chat completion */
    id: string;
}
