// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         liked: true
 *     }
 */
export interface LikeRequest {
    /** The ID of the chat completion */
    id: string;
    liked: boolean;
}
