// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListChatCompletionsRequest {
    page?: number;
    /** Results per page (clamped to 100). */
    per_page?: number;
    agent_id?: string;
    channel_id?: string;
    bible_id?: string;
    cached?: string;
    client?: string;
    config_id?: string;
    conversation_id?: string;
    device_id?: string;
    flagged?: string;
    favorited?: string;
    language?: string;
    liked?: string;
    session_id?: string;
    user_id?: string;
    min_timestamp?: string;
    max_timestamp?: string;
}
