// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ShareRequest {
    /** The ID of the chat completion */
    id: string;
    conversation_id?: string | null;
    session_id?: string | null;
    user_id?: string | null;
}
