// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token: "token"
 *     }
 */
export interface GetSharedMessagesRequest {
    /** The share token */
    token: string;
}
