// This file was auto-generated by Fern from our API Definition.

export interface GetLineChannelStatusResponse {
    status?: string | undefined;
    channel?: string | undefined;
    active?: boolean | undefined;
}
