// This file was auto-generated by Fern from our API Definition.

export const VerifyWhatsAppWebhookRequestHubMode = {
    Subscribe: "subscribe",
} as const;
export type VerifyWhatsAppWebhookRequestHubMode =
    (typeof VerifyWhatsAppWebhookRequestHubMode)[keyof typeof VerifyWhatsAppWebhookRequestHubMode];
