// This file was auto-generated by Fern from our API Definition.

export const VerifyFacebookWebhookRequestHubMode = {
    Subscribe: "subscribe",
} as const;
export type VerifyFacebookWebhookRequestHubMode =
    (typeof VerifyFacebookWebhookRequestHubMode)[keyof typeof VerifyFacebookWebhookRequestHubMode];
