// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface CorpusSearchRequest {
    query: string;
    prompt_id?: string | null;
    limit?: number | null;
    filters?: CorpusSearchRequest.Filters | null;
}

export namespace CorpusSearchRequest {
    export interface Filters {
        model?: (string | null) | undefined;
        ids?: (number[] | null) | undefined;
        types?: (string[] | null) | undefined;
        languages?: (string[] | null) | undefined;
        collection_ids?: (number[] | null) | undefined;
        contributor_ids?: (number[] | null) | undefined;
        category_ids?: (number[] | null) | undefined;
        classification_ids?: (number[] | null) | undefined;
    }
}
