// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         model: "model",
 *         id: "id",
 *         prompt_id: "prompt_id"
 *     }
 */
export interface LogCorpusReferralRedirectRequest {
    /** The model type (e.g., 'source') */
    model: string;
    /** The numeric ID of the corpus item */
    id: string;
    prompt_id: string;
    user_id?: string;
    /** URL-encoded destination to redirect to after logging the referral. */
    url?: string;
}
