// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         model: "model",
 *         id: "id",
 *         prompt_id: "prompt_id"
 *     }
 */
export interface ReferralRequest {
    /** The model type (e.g., 'source') */
    model: string;
    /** The ID of the corpus item */
    id: string;
    prompt_id: string;
    user_id?: string | null;
}
