// This file was auto-generated by Fern from our API Definition.

import type * as ApologistAgent from "../../../index.js";

export interface ListUserFlagsResponse {
    data?: ApologistAgent.UserFlag[] | undefined;
    total?: number | undefined;
    page?: number | undefined;
    per_page?: number | undefined;
}
