// This file was auto-generated by Fern from our API Definition.

/**
 * Agent-wide pause or resume result, including fan-out counts.
 */
export interface AgentPauseState {
    is_paused?: boolean | undefined;
    paused_at?: (string | null) | undefined;
    resumed_at?: (string | null) | undefined;
    /** Conversations that received a transition message. */
    emitted?: number | undefined;
    /** Conversations skipped during fan-out. */
    skipped?: number | undefined;
}
