// This file was auto-generated by Fern from our API Definition.

import type * as ApologistAgent from "../index.js";

export interface ChatCompletionResponse {
    id?: string | undefined;
    object?: string | undefined;
    created?: number | undefined;
    model?: string | undefined;
    choices?: ChatCompletionResponse.Choices.Item[] | undefined;
    usage?: ChatCompletionResponse.Usage | undefined;
    cached?: boolean | undefined;
}

export namespace ChatCompletionResponse {
    export type Choices = Choices.Item[];

    export namespace Choices {
        export interface Item {
            index?: number | undefined;
            message?: ApologistAgent.ChatMessage | undefined;
            logprobs?: (Record<string, unknown> | null) | undefined;
            finish_reason?: string | undefined;
        }
    }

    export interface Usage {
        prompt_tokens?: number | undefined;
        completion_tokens?: number | undefined;
        total_tokens?: number | undefined;
    }
}
