// This file was auto-generated by Fern from our API Definition.

export interface ChatMessage {
    role?: ChatMessage.Role | undefined;
    content?: string | undefined;
}

export namespace ChatMessage {
    export const Role = {
        System: "system",
        User: "user",
        Assistant: "assistant",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
