// This file was auto-generated by Fern from our API Definition.

/**
 * A conversation scoped to the requesting agent.
 */
export interface Conversation {
    /** Internal conversation id (UUID). */
    id?: string | undefined;
    /** Team-scoped external conversation id. */
    external_id?: (string | null) | undefined;
    agent_id?: number | undefined;
    team_id?: number | undefined;
    tags?: (Record<string, unknown> | null) | undefined;
    started_at?: string | undefined;
    ended_at?: (string | null) | undefined;
    agent_paused?: boolean | undefined;
    agent_paused_at?: (string | null) | undefined;
    agent_resumed_at?: (string | null) | undefined;
}
