// This file was auto-generated by Fern from our API Definition.

/**
 * A team-level user flag definition from the user_flags table.
 */
export interface UserFlag {
    id?: number | undefined;
    name?: string | undefined;
    /** Upstream owning user id when present (mirrored from Ignite). */
    user_id?: (number | null) | undefined;
    team_id?: (number | null) | undefined;
    synced_at?: string | undefined;
}
