// This file was auto-generated by Fern from our API Definition.

import type * as ApologistAgent from "../index.js";

export interface User {
    /** Internal user id (UUID). */
    id?: string | undefined;
    external_id?: (string | null) | undefined;
    team_id?: number | undefined;
    created_at?: string | undefined;
    migrated_at?: (string | null) | undefined;
    migrated_to_user_id?: (string | null) | undefined;
    tags?: ApologistAgent.TagRef[] | undefined;
    responder_id?: (number | null) | undefined;
}
