// This file was auto-generated by Fern from our API Definition.

/**
 * Result of scrubbing or anonymizing a user's message-adjacent text. Rows and identifiers are kept.
 */
export interface UserRedactResponse {
    /** Internal user id (UUID). */
    id?: string | undefined;
    mode?: UserRedactResponse.Mode | undefined;
    /** When the erase request was stamped. The hourly cron finishes leftover rows. */
    redact_requested_at?: (string | null) | undefined;
    /** Message rows rewritten in this request. */
    messages_redacted?: number | undefined;
    /** Message rows still waiting. Zero means this request finished the user. */
    remaining?: number | undefined;
}

export namespace UserRedactResponse {
    export const Mode = {
        Scrub: "scrub",
        Anonymize: "anonymize",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
