// This file was auto-generated by Fern from our API Definition.

/**
 * The notification configuration that produced this delivery.
 */
export interface WebhookNotificationRef {
    id: number;
    name: string;
}
