// This file was auto-generated by Fern from our API Definition.

export interface WebhookEventInfo {
    /** Stable machine-readable event key. */
    key: WebhookEventInfo.Key;
    /** Human-readable event label. */
    label: string;
    occurred_at: string;
}

export namespace WebhookEventInfo {
    /** Stable machine-readable event key. */
    export const Key = {
        PromptSubmit: "prompt_submit",
        ResponseStart: "response_start",
        ResponseEnd: "response_end",
        AutomationsEnd: "automations_end",
        ResponseLike: "response_like",
        ResponseFlag: "response_flag",
        ResponseFeedback: "response_feedback",
        ReferralClick: "referral_click",
        CtaTrigger: "cta_trigger",
        CtaClick: "cta_click",
        GuardrailTrigger: "guardrail_trigger",
        AttributionClick: "attribution_click",
        FooterClick: "footer_click",
        NewUser: "new_user",
        NewDevice: "new_device",
        NewSession: "new_session",
        NewConversation: "new_conversation",
        Error: "error",
    } as const;
    export type Key = (typeof Key)[keyof typeof Key];
}
