// This file was auto-generated by Fern from our API Definition.

/**
 * Result of an evaluation run for CTA/guardrail events.
 */
export interface WebhookEvaluation {
    score?: (number | null) | undefined;
    passed?: (boolean | null) | undefined;
    content?: (string | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
