// This file was auto-generated by Fern from our API Definition.

import type * as ApologistAgent from "../index.js";

/**
 * Canonical JSON body POSTed to a configured webhook URL. `notification`, `event`, and `agent` are always present; the remaining sections appear only when relevant to the event. Treat the payload as additive and ignore unrecognised fields.
 */
export interface WebhookPayload {
    notification: ApologistAgent.WebhookNotificationRef;
    event: ApologistAgent.WebhookEventInfo;
    agent: ApologistAgent.WebhookAgentRef;
    /** Present when the event is tied to a prompt. Includes the prompt and response plus `automations` and `tags` arrays. Shape mirrors the prompt API object. */
    completion?: (Record<string, unknown> | null) | undefined;
    /** Present when the prompt arrived via a channel. */
    channel?: ApologistAgent.WebhookNamedRef | undefined;
    /** Present alongside `channel` when the channel has a platform. */
    platform?: ApologistAgent.WebhookNamedRef | undefined;
    /** Present for cta_trigger and cta_click events. */
    cta?: ApologistAgent.WebhookCta | undefined;
    /** Present for guardrail_trigger events. */
    guardrail?: ApologistAgent.WebhookNamedRef | undefined;
    /** Present for CTA/guardrail events that ran an evaluation. */
    evaluator?: ApologistAgent.WebhookNamedRef | undefined;
    evaluation?: ApologistAgent.WebhookEvaluation | undefined;
}
