// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as ApologistAgent from "../../../index.js";

export declare namespace AgentClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Agent-wide pause and resume endpoints
 */
export class AgentClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AgentClient.Options>;

    constructor(options: AgentClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Pauses the agent globally and fans out pause transition messages to open conversations. Requires an API key.
     *
     * @param {AgentClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.agent.pauseAgent()
     */
    public pauseAgent(
        requestOptions?: AgentClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.PauseAgentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pauseAgent(requestOptions));
    }

    private async __pauseAgent(
        requestOptions?: AgentClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.PauseAgentResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                "pause",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.PauseAgentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/pause");
    }

    /**
     * Resumes the agent globally and fans out resume transition messages to open conversations. Requires an API key.
     *
     * @param {AgentClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.agent.resumeAgent()
     */
    public resumeAgent(
        requestOptions?: AgentClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.ResumeAgentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resumeAgent(requestOptions));
    }

    private async __resumeAgent(
        requestOptions?: AgentClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.ResumeAgentResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                "resume",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.ResumeAgentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/resume");
    }
}
