// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ReceiveWhatsAppMessageRequest {
    /** The channel id */
    id: string;
    /** Meta `sha256=<hex>` HMAC of the raw body keyed with the WhatsApp App Secret. Required when the channel has an App Secret configured and the webhook URL does not include an api_key. */
    "x-hub-signature-256"?: string;
    /** WhatsApp Cloud API webhook payload (`entry` + `changes`). */
    body: Record<string, unknown>;
}
