// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-signature-ed25519": "x-signature-ed25519",
 *         "x-signature-timestamp": "x-signature-timestamp",
 *         id: "id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ReceiveDiscordInteractionRequest {
    /** The channel id */
    id: string;
    /** Discord request signature (hex). */
    "x-signature-ed25519": string;
    /** Discord request timestamp. */
    "x-signature-timestamp": string;
    /** Discord interaction payload. */
    body: Record<string, unknown>;
}
