// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ReceiveTelegramUpdateRequest {
    /** The channel id */
    id: string;
    /** Telegram update payload. */
    body: Record<string, unknown>;
}
