// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ReceiveLineWebhookRequest {
    /** The channel id */
    id: string;
    /** Base64-encoded HMAC-SHA256 of the raw body keyed with the LINE channel secret. Required when the webhook URL does not include an api_key. */
    "x-line-signature"?: string;
    /** LINE webhook payload (`destination` + `events`). */
    body: Record<string, unknown>;
}
