// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ReceiveChatwootWebhookRequest {
    /** The channel id */
    id: string;
    /** `sha256=` plus hex HMAC-SHA256 of `{timestamp}.{rawBody}` keyed with the Agent Bot webhook secret. Required when the webhook URL does not include an api_key, and whenever a webhook secret is configured. */
    "X-Chatwoot-Signature"?: string;
    /** Unix timestamp used in the HMAC payload. */
    "X-Chatwoot-Timestamp"?: string;
    /** Chatwoot Agent Bot webhook payload (`event` plus message or conversation fields). */
    body: Record<string, unknown>;
}
