// This file was auto-generated by Fern from our API Definition.

import type * as ApologistAgent from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         "hub.mode": "subscribe",
 *         "hub.verify_token": "hub.verify_token"
 *     }
 */
export interface VerifyWhatsAppWebhookRequest {
    /** The channel id */
    id: string;
    "hub.mode": ApologistAgent.VerifyWhatsAppWebhookRequestHubMode;
    "hub.verify_token": string;
    "hub.challenge"?: string;
}
