// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PauseConversationRequest {
    /** The conversation UUID or team-scoped external id */
    id: string;
}
