// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as ApologistAgent from "../../../index.js";

export declare namespace ConversationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Conversation list, read, pause, and resume endpoints
 */
export class ConversationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConversationsClient.Options>;

    constructor(options: ConversationsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     *
     * @param {ApologistAgent.ListConversationsRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.conversations.listConversations()
     */
    public listConversations(
        request: ApologistAgent.ListConversationsRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.ListConversationsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listConversations(request, requestOptions));
    }

    private async __listConversations(
        request: ApologistAgent.ListConversationsRequest = {},
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.ListConversationsResponse>> {
        const { page, per_page: perPage } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            per_page: perPage,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                "conversations",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as ApologistAgent.ListConversationsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/conversations");
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     *
     * @param {ApologistAgent.GetConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.NotFoundError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.conversations.getConversation({
     *         id: "id"
     *     })
     */
    public getConversation(
        request: ApologistAgent.GetConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.GetConversationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getConversation(request, requestOptions));
    }

    private async __getConversation(
        request: ApologistAgent.GetConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.GetConversationResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                `conversations/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as ApologistAgent.GetConversationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new ApologistAgent.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/conversations/{id}");
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     *
     * @param {ApologistAgent.PauseConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.NotFoundError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.conversations.pauseConversation({
     *         id: "id"
     *     })
     */
    public pauseConversation(
        request: ApologistAgent.PauseConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.PauseConversationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pauseConversation(request, requestOptions));
    }

    private async __pauseConversation(
        request: ApologistAgent.PauseConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.PauseConversationResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                `conversations/${core.url.encodePathParam(id)}/pause`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as ApologistAgent.PauseConversationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new ApologistAgent.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/{id}/pause");
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     *
     * @param {ApologistAgent.ResumeConversationRequest} request
     * @param {ConversationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.NotFoundError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.conversations.resumeConversation({
     *         id: "id"
     *     })
     */
    public resumeConversation(
        request: ApologistAgent.ResumeConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.ResumeConversationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resumeConversation(request, requestOptions));
    }

    private async __resumeConversation(
        request: ApologistAgent.ResumeConversationRequest,
        requestOptions?: ConversationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.ResumeConversationResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                `conversations/${core.url.encodePathParam(id)}/resume`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as ApologistAgent.ResumeConversationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new ApologistAgent.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/conversations/{id}/resume");
    }
}
