// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         content: "content"
 *     }
 */
export interface EvaluatorRequest {
    /** The ID or key of the evaluator */
    id: string;
    frequency_penalty?: number | null;
    confidence_threshold?: number | null;
    content: EvaluatorRequest.Content;
    model?: string | null;
    presence_penalty?: number | null;
    reasoning_effort?: EvaluatorRequest.ReasoningEffort | null;
    verbosity?: EvaluatorRequest.Verbosity | null;
    temperature?: number | null;
    top_p?: number | null;
    /** Flat string key/value pairs substituted into `{key}` placeholders in the evaluator prompt. Reserved keys (`options`, `option_descriptions`, `criteria`) cannot be overridden. Not persisted; omitted from the response. */
    variables?: Record<string, string | null> | null;
}

export namespace EvaluatorRequest {
    export type Content = string | unknown[];
    export const ReasoningEffort = {
        Low: "low",
        Medium: "medium",
        High: "high",
    } as const;
    export type ReasoningEffort = (typeof ReasoningEffort)[keyof typeof ReasoningEffort];
    export const Verbosity = {
        Minimal: "minimal",
        Low: "low",
        Medium: "medium",
        High: "high",
    } as const;
    export type Verbosity = (typeof Verbosity)[keyof typeof Verbosity];
}
