// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         evaluationId: "evaluationId"
 *     }
 */
export interface GetEvaluationRequest {
    /** The id or key of the evaluator */
    id: string;
    /** The id or UUID of the evaluation */
    evaluationId: string;
}
