// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ListEvaluationsRequest {
    /** The ID or key of the evaluator */
    id: string;
    page?: number;
    /** Results per page (clamped to 100). */
    per_page?: number;
    min_timestamp?: string;
    max_timestamp?: string;
    min_duration?: string;
    max_duration?: string;
    min_score?: string;
    max_score?: string;
    passed?: string;
    benchmark?: string;
    benchmark_run_id?: string;
    benchmark_question_id?: string;
}
