// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentClient", () => {
    test("pauseAgent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: { is_paused: true, paused_at: "paused_at", resumed_at: "resumed_at", emitted: 1, skipped: 1 },
        };

        server.mockEndpoint().post("/pause").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agent.pauseAgent();
        expect(response).toEqual(rawResponseBody);
    });

    test("pauseAgent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/pause").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.pauseAgent();
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("pauseAgent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/pause").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.pauseAgent();
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("resumeAgent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: { is_paused: true, paused_at: "paused_at", resumed_at: "resumed_at", emitted: 1, skipped: 1 },
        };

        server.mockEndpoint().post("/resume").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agent.resumeAgent();
        expect(response).toEqual(rawResponseBody);
    });

    test("resumeAgent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/resume").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.resumeAgent();
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("resumeAgent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/resume").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.resumeAgent();
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });
});
