// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ChannelsClient", () => {
    test("getDiscordChannelStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "status", channel: "channel", active: true };

        server
            .mockEndpoint()
            .get("/channels/id/discord")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.channels.getDiscordChannelStatus({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getDiscordChannelStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/channels/id/discord")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.getDiscordChannelStatus({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("receiveDiscordInteraction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/discord")
            .header("x-signature-ed25519", "x-signature-ed25519")
            .header("x-signature-timestamp", "x-signature-timestamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.channels.receiveDiscordInteraction({
            "x-signature-ed25519": "x-signature-ed25519",
            "x-signature-timestamp": "x-signature-timestamp",
            id: "id",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(undefined);
    });

    test("receiveDiscordInteraction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/discord")
            .header("x-signature-ed25519", "signatureEd25519")
            .header("x-signature-timestamp", "signatureTimestamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveDiscordInteraction({
                "x-signature-ed25519": "signatureEd25519",
                "x-signature-timestamp": "signatureTimestamp",
                id: "id",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(ApologistAgent.BadRequestError);
    });

    test("receiveDiscordInteraction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/discord")
            .header("x-signature-ed25519", "signatureEd25519")
            .header("x-signature-timestamp", "signatureTimestamp")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveDiscordInteraction({
                "x-signature-ed25519": "signatureEd25519",
                "x-signature-timestamp": "signatureTimestamp",
                id: "id",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(ApologistAgent.UnauthorizedError);
    });

    test("receiveFacebookMessage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/facebook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.channels.receiveFacebookMessage({
            id: "id",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(undefined);
    });

    test("receiveFacebookMessage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/facebook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveFacebookMessage({
                id: "id",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("receiveFacebookMessage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/facebook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveFacebookMessage({
                id: "id",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("receiveTelegramUpdate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/telegram")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.channels.receiveTelegramUpdate({
            id: "id",
            body: {
                key: "value",
            },
        });
        expect(response).toEqual(undefined);
    });

    test("receiveTelegramUpdate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/telegram")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveTelegramUpdate({
                id: "id",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("receiveTelegramUpdate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { string: { key: "value" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/telegram")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveTelegramUpdate({
                id: "id",
                body: {
                    string: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("receiveTwilioMessage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .post("/channels/id/twilio")
            .formUrlEncodedBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.channels.receiveTwilioMessage({
            id: "id",
        });
        expect(response).toEqual(undefined);
    });

    test("receiveTwilioMessage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/twilio")
            .formUrlEncodedBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveTwilioMessage({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("receiveTwilioMessage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/channels/id/twilio")
            .formUrlEncodedBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.channels.receiveTwilioMessage({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });
});
