// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ChatClient", () => {
    test("listChatCompletions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: [{ key: "value" }], total: 1, page: 1, per_page: 1 };

        server.mockEndpoint().get("/chat/completions").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.chat.listChatCompletions();
        expect(response).toEqual(rawResponseBody);
    });

    test("listChatCompletions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/chat/completions").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.listChatCompletions();
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("listChatCompletions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/chat/completions").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.chat.listChatCompletions();
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("createChatCompletion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = {
            id: "id",
            object: "object",
            created: 1,
            model: "model",
            choices: [
                {
                    index: 1,
                    message: { role: "system", content: "content" },
                    logprobs: { logprobs: { key: "value" } },
                    finish_reason: "finish_reason",
                },
                {
                    index: 1,
                    message: { role: "system", content: "content" },
                    logprobs: { logprobs: { key: "value" } },
                    finish_reason: "finish_reason",
                },
            ],
            usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 1 },
            cached: true,
        };

        server
            .mockEndpoint()
            .post("/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.createChatCompletion({
            key: "value",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createChatCompletion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.createChatCompletion({
                key: "value",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("createChatCompletion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.createChatCompletion({
                key: "value",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("createChatCompletion (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.createChatCompletion({
                key: "value",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("likeCompletion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { liked: true };
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/like")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.likeCompletion({
            id: "id",
            liked: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("likeCompletion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { liked: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/like")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.likeCompletion({
                id: "id",
                liked: true,
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("likeCompletion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { liked: true };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/chat/completions/id/like")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.likeCompletion({
                id: "id",
                liked: true,
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("likeCompletion (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { liked: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/like")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.likeCompletion({
                id: "id",
                liked: true,
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("flagCompletion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { flagged: true };
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/flag")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.flagCompletion({
            id: "id",
            flagged: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("flagCompletion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { flagged: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/flag")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.flagCompletion({
                id: "id",
                flagged: true,
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("flagCompletion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { flagged: true };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/chat/completions/id/flag")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.flagCompletion({
                id: "id",
                flagged: true,
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("flagCompletion (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { flagged: true };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/flag")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.flagCompletion({
                id: "id",
                flagged: true,
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("feedbackCompletion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "feedback" };
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/feedback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.feedbackCompletion({
            id: "id",
            feedback: "feedback",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("feedbackCompletion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/feedback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.feedbackCompletion({
                id: "id",
                feedback: "x",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("feedbackCompletion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "x" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/chat/completions/id/feedback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.feedbackCompletion({
                id: "id",
                feedback: "x",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("feedbackCompletion (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/feedback")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.feedbackCompletion({
                id: "id",
                feedback: "x",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("shareCompletion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/share")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.shareCompletion({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("shareCompletion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/share")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.shareCompletion({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("shareCompletion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/chat/completions/id/share")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.shareCompletion({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("shareCompletion (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/chat/completions/id/share")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.shareCompletion({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("getChatCompletion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .get("/chat/completions/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.getChatCompletion({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getChatCompletion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/chat/completions/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.getChatCompletion({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("getChatCompletion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/chat/completions/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.getChatCompletion({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("getChatCompletion (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/chat/completions/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.chat.getChatCompletion({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });
});
