// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ConversationsClient", () => {
    test("listConversations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    external_id: "external_id",
                    agent_id: 1,
                    team_id: 1,
                    tags: { key: "value" },
                    started_at: "started_at",
                    ended_at: "ended_at",
                    agent_paused: true,
                    agent_paused_at: "agent_paused_at",
                    agent_resumed_at: "agent_resumed_at",
                },
            ],
            total: 1,
            page: 1,
            per_page: 1,
        };

        server.mockEndpoint().get("/conversations").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.conversations.listConversations();
        expect(response).toEqual(rawResponseBody);
    });

    test("listConversations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/conversations").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.conversations.listConversations();
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("listConversations (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/conversations").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.conversations.listConversations();
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("getConversation (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                external_id: "external_id",
                agent_id: 1,
                team_id: 1,
                tags: { key: "value" },
                started_at: "started_at",
                ended_at: "ended_at",
                agent_paused: true,
                agent_paused_at: "agent_paused_at",
                agent_resumed_at: "agent_resumed_at",
            },
        };

        server.mockEndpoint().get("/conversations/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.conversations.getConversation({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getConversation (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/conversations/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.conversations.getConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("getConversation (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/conversations/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.conversations.getConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("getConversation (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/conversations/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.conversations.getConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("pauseConversation (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                external_id: "external_id",
                agent_id: 1,
                team_id: 1,
                tags: { key: "value" },
                started_at: "started_at",
                ended_at: "ended_at",
                agent_paused: true,
                agent_paused_at: "agent_paused_at",
                agent_resumed_at: "agent_resumed_at",
            },
        };

        server
            .mockEndpoint()
            .post("/conversations/id/pause")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversations.pauseConversation({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("pauseConversation (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversations/id/pause")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversations.pauseConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("pauseConversation (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversations/id/pause")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversations.pauseConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("pauseConversation (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversations/id/pause")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversations.pauseConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("resumeConversation (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                external_id: "external_id",
                agent_id: 1,
                team_id: 1,
                tags: { key: "value" },
                started_at: "started_at",
                ended_at: "ended_at",
                agent_paused: true,
                agent_paused_at: "agent_paused_at",
                agent_resumed_at: "agent_resumed_at",
            },
        };

        server
            .mockEndpoint()
            .post("/conversations/id/resume")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversations.resumeConversation({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("resumeConversation (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversations/id/resume")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversations.resumeConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("resumeConversation (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversations/id/resume")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversations.resumeConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("resumeConversation (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversations/id/resume")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversations.resumeConversation({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });
});
