// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CorpusClient", () => {
    test("searchCorpus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = { results: [{ key: "value" }] };

        server
            .mockEndpoint()
            .post("/corpus/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.corpus.searchCorpus({
            query: "query",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchCorpus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.searchCorpus({
                query: "query",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("searchCorpus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/corpus/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.searchCorpus({
                query: "query",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("searchCorpus (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/search")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.searchCorpus({
                query: "query",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("logCorpusView (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.corpus.logCorpusView({
            model: "model",
            id: "id",
            prompt_id: "prompt_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("logCorpusView (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusView({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("logCorpusView (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/corpus/model/id/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusView({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("logCorpusView (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusView({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("logCorpusImpression (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/impression")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.corpus.logCorpusImpression({
            model: "model",
            id: "id",
            prompt_id: "prompt_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("logCorpusImpression (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/impression")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusImpression({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("logCorpusImpression (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/corpus/model/id/impression")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusImpression({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("logCorpusImpression (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/impression")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusImpression({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("logCorpusReferralRedirect (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .get("/corpus/model/id/referral")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.corpus.logCorpusReferralRedirect({
            model: "model",
            id: "id",
            prompt_id: "prompt_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("logCorpusReferralRedirect (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/corpus/model/id/referral")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusReferralRedirect({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("logCorpusReferralRedirect (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .get("/corpus/model/id/referral")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusReferralRedirect({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("logCorpusReferralRedirect (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/corpus/model/id/referral")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusReferralRedirect({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("logCorpusReferral (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/referral")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.corpus.logCorpusReferral({
            model: "model",
            id: "id",
            prompt_id: "prompt_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("logCorpusReferral (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/referral")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusReferral({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("logCorpusReferral (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/corpus/model/id/referral")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusReferral({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("logCorpusReferral (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/corpus/model/id/referral")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.corpus.logCorpusReferral({
                model: "model",
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });
});
