// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CtAsClient", () => {
    test("matchCtas (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { ctas: [{ ctas: { key: "value" } }, { ctas: { key: "value" } }] };

        server
            .mockEndpoint()
            .post("/ctas/match")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ctAs.matchCtas({
            key: "value",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("matchCtas (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/ctas/match")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ctAs.matchCtas({
                key: "value",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("matchCtas (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/ctas/match")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ctAs.matchCtas({
                key: "value",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("matchCtas (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/ctas/match")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ctAs.matchCtas({
                key: "value",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("matchCtas (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { key: "value" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/ctas/match")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ctAs.matchCtas({
                key: "value",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("logCtaClick (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .post("/ctas/id/click")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ctAs.logCtaClick({
            id: "id",
            prompt_id: "prompt_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("logCtaClick (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/ctas/id/click")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ctAs.logCtaClick({
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("logCtaClick (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/ctas/id/click")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ctAs.logCtaClick({
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("logCtaClick (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { prompt_id: "prompt_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/ctas/id/click")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ctAs.logCtaClick({
                id: "id",
                prompt_id: "prompt_id",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });
});
