// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EvaluatorsClient", () => {
    test("listEvaluations (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: [{ key: "value" }], total: 1, page: 1, per_page: 1 };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.evaluators.listEvaluations({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listEvaluations (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.listEvaluations({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("listEvaluations (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.listEvaluations({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("listEvaluations (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.listEvaluations({
                id: "id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("evaluateContent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { content: "content" };
        const rawResponseBody = { result: { key: "value" } };

        server
            .mockEndpoint()
            .post("/evaluators/id/evaluations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.evaluators.evaluateContent({
            id: "id",
            content: "content",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("evaluateContent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { content: "content" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/evaluators/id/evaluations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.evaluateContent({
                id: "id",
                content: "content",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("evaluateContent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { content: "content" };
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .post("/evaluators/id/evaluations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.evaluateContent({
                id: "id",
                content: "content",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("evaluateContent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { content: "content" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/evaluators/id/evaluations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.evaluateContent({
                id: "id",
                content: "content",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("evaluateContent (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { content: "content" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/evaluators/id/evaluations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.evaluateContent({
                id: "id",
                content: "content",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });

    test("getEvaluation (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { key: "value" } };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations/evaluationId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.evaluators.getEvaluation({
            id: "id",
            evaluationId: "evaluationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getEvaluation (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations/evaluationId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.getEvaluation({
                id: "id",
                evaluationId: "evaluationId",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("getEvaluation (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations/evaluationId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.getEvaluation({
                id: "id",
                evaluationId: "evaluationId",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("getEvaluation (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/evaluators/id/evaluations/evaluationId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.evaluators.getEvaluation({
                id: "id",
                evaluationId: "evaluationId",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });
});
