// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SharesClient", () => {
    test("getSharedMessages (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { messages: [{ key: "value" }] };

        server.mockEndpoint().get("/shares/token").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.shares.getSharedMessages({
            token: "token",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getSharedMessages (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/shares/token").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.shares.getSharedMessages({
                token: "token",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("getSharedMessages (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/shares/token").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.shares.getSharedMessages({
                token: "token",
            });
        }).rejects.toThrow(ApologistAgent.ServiceUnavailableError);
    });
});
