// This file was auto-generated by Fern from our API Definition.

import * as ApologistAgent from "../../src/api/index";
import { ApologistAgentClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UsersClient", () => {
    test("listUsers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    external_id: "external_id",
                    referral_code: "referral_code",
                    team_id: 1,
                    created_at: "created_at",
                    migrated_at: "migrated_at",
                    migrated_to_user_id: "migrated_to_user_id",
                    tags: [{}],
                    responder_id: 1,
                },
            ],
            total: 1,
            page: 1,
            per_page: 1,
        };

        server.mockEndpoint().get("/users").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.listUsers();
        expect(response).toEqual(rawResponseBody);
    });

    test("listUsers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/users").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.listUsers();
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("listUsers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/users").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.listUsers();
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("listUserFlags (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [{ id: 1, name: "name", user_id: 1, team_id: 1, synced_at: "synced_at" }],
            total: 1,
            page: 1,
            per_page: 1,
        };

        server.mockEndpoint().get("/users/flags").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.listUserFlags();
        expect(response).toEqual(rawResponseBody);
    });

    test("listUserFlags (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/users/flags").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.listUserFlags();
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("listUserFlags (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/users/flags").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.listUserFlags();
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("getUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                external_id: "external_id",
                referral_code: "referral_code",
                team_id: 1,
                created_at: "created_at",
                migrated_at: "migrated_at",
                migrated_to_user_id: "migrated_to_user_id",
                tags: [{}],
                responder_id: 1,
            },
        };

        server.mockEndpoint().get("/users/user_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.getUser({
            user_id: "user_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/users/user_id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.getUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("getUser (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/users/user_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.getUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("getUser (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/users/user_id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.users.getUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });

    test("updateUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                external_id: "external_id",
                referral_code: "referral_code",
                team_id: 1,
                created_at: "created_at",
                migrated_at: "migrated_at",
                migrated_to_user_id: "migrated_to_user_id",
                tags: [{}],
                responder_id: 1,
            },
        };

        server
            .mockEndpoint()
            .patch("/users/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.updateUser({
            user_id: "user_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/users/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.updateUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.BadRequestError);
    });

    test("updateUser (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/users/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.updateUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.ForbiddenError);
    });

    test("updateUser (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/users/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.updateUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.NotFoundError);
    });

    test("updateUser (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { success: true, errors: ["errors", "errors"] };

        server
            .mockEndpoint()
            .patch("/users/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.updateUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.UnprocessableEntityError);
    });

    test("updateUser (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApologistAgentClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/users/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.users.updateUser({
                user_id: "user_id",
            });
        }).rejects.toThrow(ApologistAgent.InternalServerError);
    });
});
