// This file was auto-generated by Fern from our API Definition.

import { BenchmarksClient } from "./api/resources/benchmarks/client/Client.js";
import { ChannelsClient } from "./api/resources/channels/client/Client.js";
import { ChatClient } from "./api/resources/chat/client/Client.js";
import { CorpusClient } from "./api/resources/corpus/client/Client.js";
import { CtAsClient } from "./api/resources/ctAs/client/Client.js";
import { EvaluatorsClient } from "./api/resources/evaluators/client/Client.js";
import { SharesClient } from "./api/resources/shares/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace ApologistAgentClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ApologistAgentClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ApologistAgentClient.Options>;
    protected _chat: ChatClient | undefined;
    protected _corpus: CorpusClient | undefined;
    protected _evaluators: EvaluatorsClient | undefined;
    protected _ctAs: CtAsClient | undefined;
    protected _users: UsersClient | undefined;
    protected _benchmarks: BenchmarksClient | undefined;
    protected _channels: ChannelsClient | undefined;
    protected _shares: SharesClient | undefined;

    constructor(options: ApologistAgentClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get chat(): ChatClient {
        return (this._chat ??= new ChatClient(this._options));
    }

    public get corpus(): CorpusClient {
        return (this._corpus ??= new CorpusClient(this._options));
    }

    public get evaluators(): EvaluatorsClient {
        return (this._evaluators ??= new EvaluatorsClient(this._options));
    }

    public get ctAs(): CtAsClient {
        return (this._ctAs ??= new CtAsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get benchmarks(): BenchmarksClient {
        return (this._benchmarks ??= new BenchmarksClient(this._options));
    }

    public get channels(): ChannelsClient {
        return (this._channels ??= new ChannelsClient(this._options));
    }

    public get shares(): SharesClient {
        return (this._shares ??= new SharesClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
