// This file was auto-generated by Fern from our API Definition.

export const ApologistAgentEnvironment = {
    Default: "https://your-agent-domain.com/api/v1",
} as const;

export type ApologistAgentEnvironment = typeof ApologistAgentEnvironment.Default;
