// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListUsersRequest {
    page?: number;
    /** Results per page (clamped to 100). */
    per_page?: number;
    external_id?: string;
    /** Comma-separated tag ids. */
    tags?: string;
    responder_id?: string;
    min_timestamp?: string;
    max_timestamp?: string;
}
