// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListUserFlagsRequest {
    page?: number;
    /** Results per page (clamped to 100). */
    per_page?: number;
}
