// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: "user_id"
 *     }
 */
export interface ScrubUserRequest {
    /** The user's external id or internal id */
    user_id: string;
}
