// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: "user_id"
 *     }
 */
export interface UserUpdateRequest {
    /** The user's external id or internal id */
    user_id: string;
    /** Your external identifier for the user. */
    external_id?: string | null;
    /** Applied tags as a mix of existing tag ids and/or default-language tag names. Unknown ids or names are rejected. Tags are mirror-owned and never created here. */
    tags?: UserUpdateRequest.Tags.Item[];
    /** Responder to persist for this user on the requesting agent. Must be active on the agent. */
    responder_id?: number;
}

export namespace UserUpdateRequest {
    export type Tags = Tags.Item[];

    export namespace Tags {
        export type Item = string | number;
    }
}
