// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as ApologistAgent from "../../../index.js";

export declare namespace UsersClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * User management endpoints
 */
export class UsersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<UsersClient.Options>;

    constructor(options: UsersClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     *
     * @param {ApologistAgent.ListUsersRequest} request
     * @param {UsersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.users.listUsers()
     */
    public listUsers(
        request: ApologistAgent.ListUsersRequest = {},
        requestOptions?: UsersClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.ListUsersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listUsers(request, requestOptions));
    }

    private async __listUsers(
        request: ApologistAgent.ListUsersRequest = {},
        requestOptions?: UsersClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.ListUsersResponse>> {
        const {
            page,
            per_page: perPage,
            external_id: externalId,
            tags,
            responder_id: responderId,
            min_timestamp: minTimestamp,
            max_timestamp: maxTimestamp,
        } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            per_page: perPage,
            external_id: externalId,
            tags,
            responder_id: responderId,
            min_timestamp: minTimestamp,
            max_timestamp: maxTimestamp,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                "users",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.ListUsersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/users");
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     *
     * @param {ApologistAgent.ListUserFlagsRequest} request
     * @param {UsersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.users.listUserFlags()
     */
    public listUserFlags(
        request: ApologistAgent.ListUserFlagsRequest = {},
        requestOptions?: UsersClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.ListUserFlagsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listUserFlags(request, requestOptions));
    }

    private async __listUserFlags(
        request: ApologistAgent.ListUserFlagsRequest = {},
        requestOptions?: UsersClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.ListUserFlagsResponse>> {
        const { page, per_page: perPage } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            per_page: perPage,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                "users/flags",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.ListUserFlagsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/users/flags");
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     *
     * @param {ApologistAgent.GetUserRequest} request
     * @param {UsersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.NotFoundError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.users.getUser({
     *         user_id: "user_id"
     *     })
     */
    public getUser(
        request: ApologistAgent.GetUserRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.GetUserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getUser(request, requestOptions));
    }

    private async __getUser(
        request: ApologistAgent.GetUserRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.GetUserResponse>> {
        const { user_id: userId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                `users/${core.url.encodePathParam(userId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.GetUserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new ApologistAgent.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/users/{user_id}");
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     *
     * @param {ApologistAgent.UserUpdateRequest} request
     * @param {UsersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.BadRequestError}
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.NotFoundError}
     * @throws {@link ApologistAgent.UnprocessableEntityError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.users.updateUser({
     *         user_id: "user_id"
     *     })
     */
    public updateUser(
        request: ApologistAgent.UserUpdateRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.UpdateUserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateUser(request, requestOptions));
    }

    private async __updateUser(
        request: ApologistAgent.UserUpdateRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.UpdateUserResponse>> {
        const { user_id: userId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                `users/${core.url.encodePathParam(userId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.UpdateUserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new ApologistAgent.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new ApologistAgent.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new ApologistAgent.UnprocessableEntityError(
                        _response.error.body as ApologistAgent.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/users/{user_id}");
    }

    /**
     * Replaces this user's message-adjacent text with a placeholder. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows.
     *
     * @param {ApologistAgent.ScrubUserRequest} request
     * @param {UsersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.NotFoundError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.users.scrubUser({
     *         user_id: "user_id"
     *     })
     */
    public scrubUser(
        request: ApologistAgent.ScrubUserRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.ScrubUserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__scrubUser(request, requestOptions));
    }

    private async __scrubUser(
        request: ApologistAgent.ScrubUserRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.ScrubUserResponse>> {
        const { user_id: userId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                `users/${core.url.encodePathParam(userId)}/scrub`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.ScrubUserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new ApologistAgent.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/users/{user_id}/scrub");
    }

    /**
     * Redacts detected personal data in this user's message-adjacent text with regex, then an optional hosted redaction service when the Agent has that option on. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows and skip text that is already redacted.
     *
     * @param {ApologistAgent.AnonymizeUserRequest} request
     * @param {UsersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ApologistAgent.ForbiddenError}
     * @throws {@link ApologistAgent.NotFoundError}
     * @throws {@link ApologistAgent.InternalServerError}
     * @throws {@link errors.ApologistAgentError}
     * @throws {@link errors.ApologistAgentTimeoutError}
     *
     * @example
     *     await client.users.anonymizeUser({
     *         user_id: "user_id"
     *     })
     */
    public anonymizeUser(
        request: ApologistAgent.AnonymizeUserRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): core.HttpResponsePromise<ApologistAgent.AnonymizeUserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__anonymizeUser(request, requestOptions));
    }

    private async __anonymizeUser(
        request: ApologistAgent.AnonymizeUserRequest,
        requestOptions?: UsersClient.RequestOptions,
    ): Promise<core.WithRawResponse<ApologistAgent.AnonymizeUserResponse>> {
        const { user_id: userId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ApologistAgentEnvironment.Default,
                `users/${core.url.encodePathParam(userId)}/anonymize`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ApologistAgent.AnonymizeUserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new ApologistAgent.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new ApologistAgent.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new ApologistAgent.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApologistAgentError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/users/{user_id}/anonymize");
    }
}
